import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="ltr" lang="en" id="smt" itemScope itemType="https://schema.org/">
      <head itemScope itemType="https://schema.org/WebSite">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.className}>
        <div id="wrapper">
          <Header />
          <div id="content"> {children} </div>
        </div>
      </body>
    </html>
  );
}
